// Package shellintegr injects OSC 133 command lifecycle markers into
// interactive shells (zsh/bash/fish) via wrapper startup files.
package shellintegr

import (
	"os"
	"path/filepath"
	"strings"
)

// DisableEnv turns the injection off when set to a non-empty value.
const DisableEnv = "ETERM_NO_SHELL_INTEGRATION"

// Wrap returns extra argv and KEY=VALUE env entries to start shell with
// OSC 133 integration. ok is false when the shell is unsupported, integration
// is disabled, or the wrapper files cannot be written; callers must then
// start the plain shell.
func Wrap(shell string) (args []string, env []string, ok bool) {
	if os.Getenv(DisableEnv) != "" {
		return nil, nil, false
	}
	name := shellName(shell)
	if name != "zsh" && name != "bash" && name != "fish" {
		return nil, nil, false
	}
	dir, err := ensureWrappers()
	if err != nil {
		return nil, nil, false
	}
	switch name {
	case "zsh":
		zdir := filepath.Join(dir, "zsh")
		return nil, []string{"ZDOTDIR=" + zdir, "ETERM_ORIG_ZDOTDIR=" + origZdotdir(zdir)}, true
	case "bash":
		return []string{"--rcfile", filepath.Join(dir, "bash", "rcfile")}, nil, true
	case "fish":
		return []string{"-C", `source "` + filepath.Join(dir, "fish", "init.fish") + `"`}, nil, true
	}
	return nil, nil, false
}

// TmuxCommand returns a shell-command string for `tmux new-session` that
// starts the user's $SHELL with OSC 133 integration.
func TmuxCommand() (string, bool) {
	shell := strings.TrimSpace(os.Getenv("SHELL"))
	if shell == "" {
		return "", false
	}
	args, env, ok := Wrap(shell)
	if !ok {
		return "", false
	}
	var b strings.Builder
	for _, kv := range env {
		b.WriteString(shQuote(kv))
		b.WriteByte(' ')
	}
	if shellName(shell) == "bash" {
		b.WriteString("ETERM_SHELL_LOGIN=1 ")
	}
	b.WriteString("exec ")
	b.WriteString(shQuote(shell))
	// tmux starts a login shell by default; keep that for zsh/fish.
	switch shellName(shell) {
	case "zsh", "fish":
		b.WriteString(" -l")
	}
	for _, a := range args {
		b.WriteByte(' ')
		b.WriteString(shQuote(a))
	}
	return b.String(), true
}

func shellName(shell string) string {
	return strings.ToLower(filepath.Base(strings.TrimSpace(shell)))
}

func origZdotdir(wrapperZdir string) string {
	orig := os.Getenv("ZDOTDIR")
	if orig == "" || orig == wrapperZdir {
		home, err := os.UserHomeDir()
		if err != nil {
			return ""
		}
		return home
	}
	return orig
}

func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func ensureWrappers() (string, error) {
	base, err := os.UserCacheDir()
	if err != nil || base == "" {
		base = os.TempDir()
	}
	dir := filepath.Join(base, "eterm", "shell-integration")
	files := []struct{ rel, content string }{
		{filepath.Join("zsh", ".zshenv"), zshZshenv(dir)},
		{filepath.Join("zsh", ".zprofile"), zshZprofile},
		{filepath.Join("zsh", ".zshrc"), zshZshrc},
		{filepath.Join("bash", "rcfile"), bashRcfile},
		{filepath.Join("fish", "init.fish"), fishInit},
	}
	for _, f := range files {
		path := filepath.Join(dir, f.rel)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return "", err
		}
		if existing, err := os.ReadFile(path); err == nil && string(existing) == f.content {
			continue
		}
		if err := os.WriteFile(path, []byte(f.content), 0644); err != nil {
			return "", err
		}
	}
	return dir, nil
}

func zshZshenv(dir string) string {
	zdir := shQuote(filepath.Join(dir, "zsh"))
	return `# eTerm shell integration (OSC 133). Regenerated by eTerm, do not edit.
[[ -f "${ETERM_ORIG_ZDOTDIR:-$HOME}/.zshenv" ]] && source "${ETERM_ORIG_ZDOTDIR:-$HOME}/.zshenv"
# ZDOTDIR is already the wrapper dir here (we were found through it). Only a
# .zshenv that points it elsewhere counts as a user override; otherwise fall
# back to the pre-wrapper dir, never the wrapper itself (that would make the
# .zshrc wrapper source itself recursively).
if [[ -n "$ZDOTDIR" && "$ZDOTDIR" != ` + zdir + ` ]]; then
  export ETERM_USER_ZDOTDIR="$ZDOTDIR"
else
  export ETERM_USER_ZDOTDIR="${ETERM_ORIG_ZDOTDIR:-$HOME}"
fi
export ZDOTDIR=` + zdir + `
`
}

const zshZprofile = `# eTerm shell integration (OSC 133). Regenerated by eTerm, do not edit.
[[ "${ETERM_USER_ZDOTDIR:-$HOME}" != "$ZDOTDIR" && -f "${ETERM_USER_ZDOTDIR:-$HOME}/.zprofile" ]] && source "${ETERM_USER_ZDOTDIR:-$HOME}/.zprofile"
`

const zshZshrc = `# eTerm shell integration (OSC 133). Regenerated by eTerm, do not edit.
[[ "${ETERM_USER_ZDOTDIR:-$HOME}" != "$ZDOTDIR" && -f "${ETERM_USER_ZDOTDIR:-$HOME}/.zshrc" ]] && source "${ETERM_USER_ZDOTDIR:-$HOME}/.zshrc"
export ZDOTDIR="${ETERM_USER_ZDOTDIR:-$HOME}"
unset ETERM_USER_ZDOTDIR
autoload -Uz add-zsh-hook
__eterm_osc133_precmd() {
  local __eterm_ec=$?
  if [[ -n "${__eterm_osc133_in_cmd:-}" ]]; then
    printf '\033]133;D;%d\007' "$__eterm_ec"
    unset __eterm_osc133_in_cmd
  fi
  printf '\033]133;A\007'
  printf '\033]133;B\007'
}
__eterm_osc133_preexec() {
  printf '\033]133;C\007'
  __eterm_osc133_in_cmd=1
}
add-zsh-hook precmd __eterm_osc133_precmd
add-zsh-hook preexec __eterm_osc133_preexec
`

const bashRcfile = `# eTerm shell integration (OSC 133). Regenerated by eTerm, do not edit.
# --rcfile makes bash non-login; ETERM_SHELL_LOGIN=1 restores login startup.
if [[ "${ETERM_SHELL_LOGIN:-0}" == "1" ]]; then
  [[ -f /etc/profile ]] && source /etc/profile
  if [[ -f "$HOME/.bash_profile" ]]; then
    source "$HOME/.bash_profile"
  elif [[ -f "$HOME/.bash_login" ]]; then
    source "$HOME/.bash_login"
  elif [[ -f "$HOME/.profile" ]]; then
    source "$HOME/.profile"
  fi
else
  [[ -f /etc/bash.bashrc ]] && source /etc/bash.bashrc
  [[ -f "$HOME/.bashrc" ]] && source "$HOME/.bashrc"
fi
__eterm_osc133_precmd() {
  local __eterm_ec=$?
  __eterm_osc133_in_prompt=1
  if [[ -n "${__eterm_osc133_in_cmd:-}" ]]; then
    printf '\033]133;D;%s\007' "$__eterm_ec"
    unset __eterm_osc133_in_cmd
  fi
  printf '\033]133;A\007'
  printf '\033]133;B\007'
}
__eterm_osc133_prompt_done() {
  unset __eterm_osc133_in_prompt
}
__eterm_osc133_preexec() {
  if [[ -n "${__eterm_user_debug_trap:-}" ]]; then
    eval "$__eterm_user_debug_trap" || true
  fi
  [[ -z "${__eterm_osc133_in_prompt:-}" ]] || return
  case "$BASH_COMMAND" in
    *__eterm_osc133_precmd*|*__eterm_osc133_prompt_done*) return ;;
  esac
  printf '\033]133;C\007'
  __eterm_osc133_in_cmd=1
}
__eterm_osc133_normalize_prompt_command() {
  local __eterm_joined="" __eterm_part
  if [[ "$(declare -p PROMPT_COMMAND 2>/dev/null)" == "declare -a"* ]]; then
    for __eterm_part in "${PROMPT_COMMAND[@]}"; do
      [[ -n "$__eterm_part" ]] || continue
      if [[ -n "$__eterm_joined" ]]; then
        __eterm_joined="$__eterm_joined;$__eterm_part"
      else
        __eterm_joined="$__eterm_part"
      fi
    done
    PROMPT_COMMAND="$__eterm_joined"
  fi
  while [[ "${PROMPT_COMMAND:-}" == *[[:space:]\;] ]]; do
    PROMPT_COMMAND="${PROMPT_COMMAND%?}"
  done
}
__eterm_osc133_normalize_prompt_command
PROMPT_COMMAND="__eterm_osc133_precmd${PROMPT_COMMAND:+;${PROMPT_COMMAND}}"
PROMPT_COMMAND="${PROMPT_COMMAND};__eterm_osc133_prompt_done"
__eterm_debug_trap_spec="$(trap -p DEBUG)"
if [[ -n "$__eterm_debug_trap_spec" ]]; then
  __eterm_debug_trap_cmd="${__eterm_debug_trap_spec#trap -- }"
  __eterm_debug_trap_cmd="${__eterm_debug_trap_cmd% DEBUG}"
  eval "__eterm_user_debug_trap=$__eterm_debug_trap_cmd"
fi
unset __eterm_debug_trap_spec __eterm_debug_trap_cmd
unset -f __eterm_osc133_normalize_prompt_command
# Arm DEBUG last so this rcfile itself emits no fake C/D markers.
trap '__eterm_osc133_preexec' DEBUG
`

const fishInit = `# eTerm shell integration (OSC 133). Regenerated by eTerm, do not edit.
function __eterm_osc133_prompt --on-event fish_prompt
    if set -q __eterm_osc133_in_cmd
        printf '\033]133;D;%s\007' $status
        set -e __eterm_osc133_in_cmd
    end
    printf '\033]133;A\007'
    printf '\033]133;B\007'
end
function __eterm_osc133_preexec --on-event fish_preexec
    printf '\033]133;C\007'
    set -g __eterm_osc133_in_cmd 1
end
`
